name: Build and Test

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: npm install and build
      run: npm ci
    - uses: actions/cache@v2
      with:
        path: .solc-bin
        key: ${{ hashFiles('solc-versions.json') }}
    - name: test
      run: npm test
